onEvent('player.logged_in', event => {
	// Check if player doesn't have "starting_items" stage yet
	if (!event.player.stages.has('starting_items')) {
	  // Add the stage
	  event.player.stages.add('starting_items')
	  // Give some items to player

   	  event.player.give(Item.of('akashictome:tome','{theoneprobe: {id: "theoneprobe:probenote", Count: 1b}, patchouli_10: {id: "patchouli:guide_book", Count: 1b, tag: {"akashictome:definedMod": "patchouli_10", "patchouli:book": "naturesaura:book"}}, ftbquests: {id: "ftbquests:book", Count: 1b}, alexsmobs: {id: "alexsmobs:animal_dictionary", Count: 1b}, patchouli_2: {id: "patchouli:guide_book", Count: 1b, tag: {"akashictome:definedMod": "patchouli_2", "patchouli:book": "mysticalagriculture:guide"}}, patchouli_3: {id: "patchouli:guide_book", Count: 1b, tag: {"akashictome:definedMod": "patchouli_3", "patchouli:book": "pneumaticcraft:book"}}, patchouli_0: {id: "patchouli:guide_book", Count: 1b, tag: {"akashictome:definedMod": "patchouli_0", "patchouli:book": "thermal:guidebook"}}, patchouli_1: {id: "patchouli:guide_book", Count: 1b, tag: {"akashictome:definedMod": "patchouli_1", "patchouli:book": "allthemodium:allthemodium"}}, patchouli: {id: "patchouli:guide_book", Count: 1b, tag: {"patchouli:book": "apotheosis:apoth_chronicle"}}, croptopia: {id: "croptopia:guide", Count: 1b}, cookingforblockheads: {id: "cookingforblockheads:recipe_book", Count: 1b}, malum: {id: "malum:encyclopedia_arcana", Count: 1b}, securitycraft: {id: "securitycraft:sc_manual", Count: 1b}, integratedtunnels: {id: "integrateddynamics:on_the_dynamics_of_integration", Count: 1b}, patchouli_8: {id: "patchouli:guide_book", Count: 1b, tag: {"akashictome:definedMod": "patchouli_8", "patchouli:book": "advancedperipherals:manual"}}, patchouli_9: {id: "patchouli:guide_book", Count: 1b, tag: {"akashictome:definedMod": "patchouli_9", "patchouli:book": "littlelogistics:guide"}}, patchouli_6: {id: "patchouli:guide_book", Count: 1b, tag: {"akashictome:definedMod": "patchouli_6", "patchouli:book": "engineersdecor:engineersdecor_manual"}}, occultism: {id: "occultism:dictionary_of_spirits", Count: 1b}, mahoutsukai: {id: "mahoutsukai:guidebook", Count: 1b}, patchouli_7: {id: "patchouli:guide_book", Count: 1b, tag: {"akashictome:definedMod": "patchouli_7", "patchouli:book": "modularrouters:book"}}, solcarrot: {id: "solcarrot:food_book", Count: 1b}, patchouli_4: {id: "patchouli:guide_book", Count: 1b, tag: {"akashictome:definedMod": "patchouli_4", "patchouli:book": "cyclic:cyclic_guide_book"}}, patchouli_5: {id: "patchouli:guide_book", Count: 1b, tag: {"akashictome:definedMod": "patchouli_5", "patchouli:book": "extendedcrafting:guide"}}, byg: {id: "byg:biomepedia", Count: 1b}, exoticbirds: {id: "exoticbirds:bird_book", Count: 1b}}'))
	}
  })