[general]
	clientID = 762726289341677668
	enabled = true
	debugging = false
	configScreen = true
	launcherIntegration = false
	version = 12

[init]
	enabled = true
	description = "End of Mine is loading"
	state = "Game Starting..."
	largeImageKey = "modpack_logo"
	largeImageText = "It's All that and the kitchen sink"
	smallImageKey = ""
	smallImageText = "%mods% mods installed"
	buttons = []

[main_menu]
	enabled = true
	description = "%player% is currently lazy"
	state = "Chilling in the menu"
	largeImageKey = "modpack_logo"
	largeImageText = "It's All that and the kitchen sink"
	smallImageKey = ""
	smallImageText = "%mods% mods installed"
	buttons = []

[server_list]
	enabled = true
	description = "%player% is looking for a server"
	state = "Searching for friends"
	largeImageKey = "modpack_logo"
	largeImageText = "It's All that and the kitchen sink"
	smallImageKey = ""
	smallImageText = "%mods% mods installed"
	buttons = []

[join_game]
	enabled = true
	description = "%player% is joining a game"
	state = "Joining Game"
	largeImageKey = "modpack_logo"
	largeImageText = "It's All that and the kitchen sink"
	smallImageKey = ""
	smallImageText = "%mods% mods installed"
	buttons = []

[single_player]
	enabled = true
	description = "Currently In %world%"
	state = "Playing lonely mode"
	largeImageKey = "modpack_logo"
	largeImageText = "It's All that and the kitchen sink"
	smallImageKey = ""
	smallImageText = "%mods% mods installed"
	buttons = []

[multi_player]
	enabled = true
	description = "Playing on End Of Mine with %players% players"
	state = "Playing online"
	largeImageKey = "modpack_logo"
	largeImageText = "It's All that and the kitchen sink"
	smallImageKey = ""
	smallImageText = "%mods% mods installed"
	buttons = []

[generic]
	description = "Playing End of Mine 1.18 Modpack"
	state = ""
	largeImageKey = "modpack_logo"
	largeImageText = "It's All that and the kitchen sink"
	smallImageKey = ""
	smallImageText = "%mods% mods installed"
	buttons = []

[dimension_overrides]
	enabled = false

	[[dimension_overrides.dimensions]]
		name = "overworld"
		description = "%player% is in The Overworld"
		state = ""
		largeImageKey = "overworld"
		largeImageText = "In the Overworld"
		smallImageKey = "mclogo"
		smallImageText = "%mods% mods installed"

	[[dimension_overrides.dimensions]]
		name = "the_nether"
		description = "%player% is in The Nether"
		state = ""
		largeImageKey = "nether"
		largeImageText = "In the Nether"
		smallImageKey = "mclogo"
		smallImageText = "%mods% mods installed"

	[[dimension_overrides.dimensions]]
		name = "the_end"
		description = "%player% is in The End"
		state = ""
		largeImageKey = "end"
		largeImageText = "In the End"
		smallImageKey = "mclogo"
		smallImageText = "%mods% mods installed"


